apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-002
  labels:
    app: curl-002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-002
  template:
    metadata:
      labels:
        app: curl-002
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ['sh', '-c', "sleep 3600"]