apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-001
  labels:
    app: curl-001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-001
  template:
    metadata:
      labels:
        app: curl-001
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: ['sh', '-c', "sleep 3600"]
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-002
  labels:
    app: curl-002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-002
  template:
    metadata:
      labels:
        app: curl-002
    spec:
      containers:
      - name: curl-002
        image: curlimages/curl
        command: ['sh', '-c', "sleep 3600"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-003
  labels:
    app: curl-003
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-003
  template:
    metadata:
      labels:
        app: curl-003
    spec:
      containers:
      - name: curl-003
        image: curlimages/curl
        command: ['sh', '-c', "sleep 3600"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-004
  labels:
    app: curl-004
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-004
  template:
    metadata:
      labels:
        app: curl-004
    spec:
      containers:
      - name: curl-004
        image: curlimages/curl
        command: ['sh', '-c', "sleep 3600"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-000
  labels:
    app: curl-000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-000
  template:
    metadata:
      labels:
        app: curl-000
    spec:
      containers:
      - name: curl-000
        image: curlimages/curl
        command: ['sh', '-c', "sleep 3600"]